"""Schemas for the Skill Normalization and ESCO Intelligence module."""

from pydantic import BaseModel, Field


class RawSkill(BaseModel):
    """Extracted raw skill input payload."""

    name: str = Field(..., description="The name of the extracted raw skill")
    confidence: float | None = Field(
        None, description="The confidence score of the raw extraction"
    )


class EscoSkill(BaseModel):
    """Canonical ESCO taxonomy skill representation."""

    esco_id: str = Field(..., description="Unique ID / URI of the ESCO skill")
    name: str = Field(..., description="Canonical ESCO skill term")
    description: str | None = Field(
        None, description="Description of the skill concept"
    )
    alternative_labels: list[str] = Field(
        default_factory=list, description="Alternative names or aliases for the skill"
    )


class SkillCandidate(BaseModel):
    """Candidate match from the taxonomy."""

    esco_skill: EscoSkill = Field(..., description="The taxonomy skill details")
    score: float = Field(..., description="Score generated by the matching strategy")
    match_method: str = Field(
        ..., description="Method used to match (exact, alias, fuzzy, embedding)"
    )


class NormalizedSkill(BaseModel):
    """Final normalized skill mapping output."""

    raw_skill: str = Field(..., description="The original extracted raw skill term")
    normalized_skill: str = Field(
        ..., description="The canonical normalized ESCO skill term"
    )
    esco_id: str = Field(..., description="Unique ID / URI of the mapped ESCO skill")
    confidence: float = Field(..., description="Overall confidence score for the match")
    match_method: str = Field(
        ..., description="The matching method used (exact, alias, fuzzy, embedding)"
    )


class MatchResult(BaseModel):
    """Matches listing for debug and ranking purposes."""

    raw_skill: str = Field(..., description="The raw skill being mapped")
    candidates: list[SkillCandidate] = Field(
        default_factory=list, description="List of possible taxonomy match candidates"
    )


class NormalizationResult(BaseModel):
    """Response envelope for the normalization service."""

    normalized_skills: list[NormalizedSkill] = Field(
        default_factory=list, description="List of successfully normalized skills"
    )
