"""add_pipeline_state_to_processing_runs

Revision ID: 91c8b91e6e90
Revises: 83573ee5e619
Create Date: 2026-06-12 11:20:53.161656

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "91c8b91e6e90"
down_revision: Union[str, Sequence[str], None] = "83573ee5e619"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "processing_runs", sa.Column("pipeline_state", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("processing_runs", "pipeline_state")
    # ### end Alembic commands ###
